apiVersion: training.eduk8s.io/v1alpha1
kind: Workshop
metadata:
  name: lab-examiner-test
spec:
  vendor: eduk8s.io
  title: Examiner Test
  description: Workshop environment to test automatic evaluation of cluster state
  content: github.com/eduk8s-tests/lab-examiner-test
  session:
    budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
    ingresses:
    - name: examiner
      port: 11111
