apiVersion: training.eduk8s.io/v1alpha1
kind: Workshop
metadata:
  name: lab-markdown-sample
spec:
  title: Markdown Sample
  description: A sample workshop using Markdown
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/eduk8s/lab-markdown-sample
  #image: quay.io/eduk8s/lab-markdown-sample:master
  content: github.com/eduk8s/lab-markdown-sample
  session:
    budget: small
    applications:
      console:
        enabled: true
      editor:
        enabled: true
